ts=1.e-4;
t=-0.04:ts:0.04;
m_sig=triangle((t+0.01)/0.01)-triangle((t-0.01)/0.01);
Lm_sig=length(m_sig);
lfft=length(t);
lfft=2^ceil(log2(lfft));
freqm=[-lfft/2:lfft/2-1]/(lfft*ts);
M_sig=fftshift(fft(m_sig,lfft));
%modulation
fc=300;
s_dsb=m_sig.*cos(2*pi*fc*t);
S_dsb=fftshift(fft(s_dsb,lfft));
L_isb=floor(fc*ts*lfft);
SSBFILTER=ones(1,lfft);
SSBFILTER(lfft/2-L_isb+1:lfft/2+L_isb)=zeros(1,2*L_isb);
S_ssb=S_dsb.*SSBFILTER;
s_ssb=real(ifft(fftshift(S_ssb)));
s_ssb=s_ssb(1:Lm_sig);
s_dem=s_ssb.*cos(2*3.14*fc*t);
h=fir1(40,[150*ts]);
s_rec=filter(h,1,s_dem);
figure(1);plot(t,s_rec);
figure(2);plot(t,s_ssb)

